name: CD Test

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 ci-job:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Install python
     uses: actions/setup-python@v4
     with: 
      python-version: "3.10"
   - name: Run the testing
     run: python test.py
 cd-job:
  runs-on: ubuntu-latest
  needs: [ci-job]
  steps:
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Build and push
     uses: docker/build-push-action@v5
     with:
      push: true
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
  