name: Environment testing

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 ci-job:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Install python
     uses: actions/setup-python@v4
     with: 
      python-version: "3.10"
   - name: Run the testing
     run: python ${{secrets.TMP_FILE}}
     env:
      TMP_IMPORTANT_VALUE: ${{secrets.TMP_VALUE}}
